<template>
  <div v-if="visible" class="modal-overlay" @click="closeModal">
    <div class="modal-content" @click.stop>
      <div class="modal-header">
        <h5 class="modal-title">
          <i class="bi bi-file-earmark-text me-2"></i>Report Details
        </h5>
        <button type="button" class="btn-close" @click="closeModal"></button>
      </div>

      <div class="modal-body">
        <div v-if="loading" class="text-center py-4">
          <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
          <p class="mt-2 text-muted">Loading report details...</p>
        </div>

        <div v-else-if="report">
          <!-- Report Header -->
          <div class="report-header mb-4">
            <div class="d-flex justify-content-between align-items-start">
              <div>
                <h4 class="mb-2">{{ report.name }}</h4>
                <p class="text-muted mb-2">{{ report.description }}</p>
                <div class="d-flex gap-2">
                  <span class="badge" :class="getReportTypeBadgeClass(report.type)">
                    {{ formatReportType(report.type) }}
                  </span>
                  <span class="badge" :class="getStatusBadgeClass(report.status)">
                    {{ formatStatus(report.status) }}
                  </span>
                </div>
              </div>
              <div class="text-end">
                <small class="text-muted">Generated: {{ formatDateTime(report.created_at) }}</small>
              </div>
            </div>
          </div>

          <!-- Report Details -->
          <div class="row">
            <div class="col-md-6">
              <div class="detail-section">
                <h6 class="section-title">Report Information</h6>
                <div class="detail-item">
                  <strong>Report ID:</strong> {{ report.id }}
                </div>
                <div class="detail-item">
                  <strong>Type:</strong>
                  <span class="badge ms-2" :class="getReportTypeBadgeClass(report.type)">
                    {{ formatReportType(report.type) }}
                  </span>
                </div>
                <div class="detail-item">
                  <strong>Format:</strong> {{ report.format?.toUpperCase() || 'N/A' }}
                </div>
                <div class="detail-item">
                  <strong>Generated By:</strong> {{ report.generated_by?.name || 'System' }}
                </div>
                <div class="detail-item">
                  <strong>Status:</strong>
                  <span class="badge ms-2" :class="getStatusBadgeClass(report.status)">
                    {{ formatStatus(report.status) }}
                  </span>
                </div>
                <div class="detail-item">
                  <strong>File Size:</strong> {{ formatFileSize(report.size) }}
                </div>
              </div>
            </div>

            <div class="col-md-6">
              <div class="detail-section">
                <h6 class="section-title">Date Range & Parameters</h6>
                <div class="detail-item">
                  <strong>Date Range:</strong> {{ report.date_range || 'N/A' }}
                </div>
                <div class="detail-item">
                  <strong>Start Date:</strong> {{ formatDate(report.parameters?.start_date) }}
                </div>
                <div class="detail-item">
                  <strong>End Date:</strong> {{ formatDate(report.parameters?.end_date) }}
                </div>
                <div class="detail-item">
                  <strong>Filters Applied:</strong> {{ report.parameters?.filters ? 'Yes' : 'No' }}
                </div>
                <div class="detail-item">
                  <strong>Records Count:</strong> {{ report.records_count || 'N/A' }}
                </div>
                <div class="detail-item">
                  <strong>Generation Time:</strong> {{ report.generation_time ? report.generation_time + 's' : 'N/A' }}
                </div>
              </div>
            </div>
          </div>

          <!-- Report Parameters -->
          <div v-if="report.parameters" class="mt-4">
            <h6 class="section-title">Report Parameters</h6>
            <div class="parameters-data">
              <pre>{{ JSON.stringify(report.parameters, null, 2) }}</pre>
            </div>
          </div>

          <!-- Report Summary -->
          <div v-if="report.summary" class="mt-4">
            <h6 class="section-title">Report Summary</h6>
            <div class="summary-data">
              <pre>{{ JSON.stringify(report.summary, null, 2) }}</pre>
            </div>
          </div>

          <!-- Report Preview -->
          <div v-if="report.preview_data" class="mt-4">
            <h6 class="section-title">Preview Data</h6>
            <div class="preview-data">
              <div class="table-responsive">
                <table class="table table-sm table-bordered">
                  <thead>
                    <tr>
                      <th v-for="(header, index) in report.preview_headers" :key="index">
                        {{ header }}
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="(row, index) in report.preview_data" :key="index">
                      <td v-for="(cell, cellIndex) in row" :key="cellIndex">
                        {{ cell }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <!-- Report Actions -->
          <div class="report-actions mt-4">
            <div class="d-flex gap-2">
              <button class="btn btn-outline-primary" @click="downloadReport" :disabled="report.status !== 'completed'">
                <i class="bi bi-download me-1"></i>Download
              </button>
              <button v-if="report.status === 'completed'" class="btn btn-outline-info" @click="viewReport">
                <i class="bi bi-eye me-1"></i>View Full Report
              </button>
              <button v-if="report.status === 'failed'" class="btn btn-outline-warning" @click="retryGeneration">
                <i class="bi bi-arrow-repeat me-1"></i>Retry
              </button>
              <button class="btn btn-outline-secondary" @click="duplicateReport">
                <i class="bi bi-copy me-1"></i>Duplicate
              </button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" @click="closeModal">Close</button>
        <button type="button" class="btn btn-danger" @click="$emit('delete-report', report)">Delete Report</button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AdminReportDetailModal',
  props: {
    visible: {
      type: Boolean,
      default: false
    },
    reportId: {
      type: [Number, String],
      default: null
    }
  },
  emits: ['close', 'delete-report'],
  data() {
    return {
      report: null,
      loading: false
    };
  },
  watch: {
    visible(newVal) {
      if (newVal && this.reportId) {
        this.fetchReportDetails();
      }
    },
    reportId(newVal) {
      if (newVal && this.visible) {
        this.fetchReportDetails();
      }
    }
  },
  methods: {
    async fetchReportDetails() {
      if (!this.reportId) return;

      this.loading = true;
      try {
        const response = await fetch(`/api/admin/reports/${this.reportId}`, {
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('token')}`,
            'Content-Type': 'application/json'
          }
        });

        if (!response.ok) {
          throw new Error('Failed to fetch report details');
        }

        this.report = await response.json();
      } catch (error) {
        console.error('Error fetching report details:', error);
      } finally {
        this.loading = false;
      }
    },

    closeModal() {
      this.$emit('close');
    },

    formatDate(dateString) {
      if (!dateString) return 'N/A';
      return new Date(dateString).toLocaleDateString();
    },

    formatDateTime(dateString) {
      if (!dateString) return 'N/A';
      return new Date(dateString).toLocaleString();
    },

    formatFileSize(bytes) {
      if (!bytes) return '0 B';
      const sizes = ['B', 'KB', 'MB', 'GB'];
      const i = Math.floor(Math.log(bytes) / Math.log(1024));
      return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];
    },

    formatReportType(type) {
      const typeMap = {
        'user': 'User Report',
        'project': 'Project Report',
        'task': 'Task Report',
        'file': 'File Report',
        'system': 'System Report'
      };
      return typeMap[type] || type;
    },

    formatStatus(status) {
      const statusMap = {
        'completed': 'Completed',
        'generating': 'Generating',
        'failed': 'Failed'
      };
      return statusMap[status] || status;
    },

    getReportTypeBadgeClass(type) {
      const classMap = {
        'user': 'bg-primary',
        'project': 'bg-success',
        'task': 'bg-info',
        'file': 'bg-warning',
        'system': 'bg-danger'
      };
      return classMap[type] || 'bg-secondary';
    },

    getStatusBadgeClass(status) {
      const classMap = {
        'completed': 'bg-success',
        'generating': 'bg-warning',
        'failed': 'bg-danger'
      };
      return classMap[status] || 'bg-secondary';
    },

    downloadReport() {
      if (this.report && this.report.download_url) {
        window.open(this.report.download_url, '_blank');
      }
    },

    viewReport() {
      // TODO: Implement full report viewing
      console.log('View full report:', this.report);
    },

    retryGeneration() {
      // TODO: Implement report regeneration
      console.log('Retry report generation:', this.report);
    },

    duplicateReport() {
      // TODO: Implement report duplication
      console.log('Duplicate report:', this.report);
    }
  }
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1050;
}

.modal-content {
  background: white;
  border-radius: 8px;
  width: 90%;
  max-width: 1000px;
  max-height: 90vh;
  overflow-y: auto;
}

.modal-header {
  padding: 1rem 1.5rem;
  border-bottom: 1px solid #dee2e6;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-title {
  margin: 0;
  font-size: 1.25rem;
  font-weight: 500;
}

.btn-close {
  background: none;
  border: none;
  font-size: 1.5rem;
  cursor: pointer;
  opacity: 0.5;
}

.btn-close:hover {
  opacity: 1;
}

.modal-body {
  padding: 1.5rem;
}

.modal-footer {
  padding: 1rem 1.5rem;
  border-top: 1px solid #dee2e6;
  display: flex;
  justify-content: flex-end;
  gap: 0.5rem;
}

.report-header {
  border-bottom: 2px solid #e9ecef;
  padding-bottom: 1rem;
}

.detail-section {
  margin-bottom: 1.5rem;
}

.section-title {
  font-weight: 600;
  color: #495057;
  margin-bottom: 1rem;
  border-bottom: 2px solid #e9ecef;
  padding-bottom: 0.5rem;
}

.detail-item {
  margin-bottom: 0.75rem;
  font-size: 0.875rem;
}

.parameters-data pre,
.summary-data pre {
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 4px;
  padding: 1rem;
  font-size: 0.75rem;
  overflow-x: auto;
  max-height: 200px;
  overflow-y: auto;
}

.preview-data {
  background: #f8f9fa;
  border: 1px solid #dee2e6;
  border-radius: 4px;
  padding: 1rem;
  max-height: 300px;
  overflow-y: auto;
}

.preview-data table {
  margin: 0;
}

.report-actions {
  border-top: 1px solid #dee2e6;
  padding-top: 1rem;
}
</style>
